"""Corrected the foreign key relations

Revision ID: 4d54b808e917
Revises: dccf7108a3be
Create Date: 2025-03-02 15:27:27.783648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d54b808e917'
down_revision = 'dccf7108a3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asha_worker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointment_asha_worker_id', 'users', ['asha_worker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asha_worker_id')

    # ### end Alembic commands ###
