"""Removed phone number field

Revision ID: 59a3cfbe0d81
Revises: 948bbc40e48f
Create Date: 2025-03-02 13:26:00.370178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a3cfbe0d81'
down_revision = '948bbc40e48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False))

    # ### end Alembic commands ###
