"""added  phone number field

Revision ID: 686474105a4d
Revises: 59a3cfbe0d81
Create Date: 2025-03-02 13:30:26.737358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686474105a4d'
down_revision = '59a3cfbe0d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
