"""Add patient_joined, prescription_file, consultation_date to Consultation

Revision ID: 804800cffa74
Revises: 686474105a4d
Create Date: 2025-03-02 14:10:25.697066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804800cffa74'
down_revision = '686474105a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_joined', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prescription_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('consultation_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('consultation_date')
        batch_op.drop_column('prescription_file')
        batch_op.drop_column('patient_joined')

    # ### end Alembic commands ###
