"""Initial schema with all tables

Revision ID: d12dd3441713
Revises: 804800cffa74
Create Date: 2025-03-02 14:20:10.302894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12dd3441713'
down_revision = '804800cffa74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('time_slot', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('prescription_file', sa.String(length=255), nullable=True))

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('prescription_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_file', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('prescription_file')
        batch_op.drop_column('status')
        batch_op.drop_column('time_slot')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
