"""Removed unwated fields and cleared redundancy

Revision ID: dccf7108a3be
Revises: d12dd3441713
Create Date: 2025-03-02 14:35:36.514592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccf7108a3be'
down_revision = 'd12dd3441713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_doctor', sa.String(length=120), nullable=False))
        batch_op.drop_column('blood_group')
        batch_op.drop_column('age')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blood_group')
        batch_op.drop_column('age')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('type_of_doctor')

    # ### end Alembic commands ###
